//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyKarakoyWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int Id { get; set; }
        public int Count { get; set; }
        public string Name { get; set; }
        public string Size { get; set; }
        public int Price { get; set; }
        public string Image { get; set; }
    }
}
