//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyKarakoyWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
    
        public string Description { get; set; }
        public Nullable<byte> Size { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Info { get; set; }
        public string Price { get; set; }
        public string Image { get; set; }
         
        public override string ToString()
        {
            return Name;
        }
        public virtual Category Category { get; set; }
    }
}
